name: Run Unit Test 

on: 
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: shibukv/nativebuildtools:0.0.1

    steps:
      - 
        name: Checkout artifacts
        uses: actions/checkout@v3
       
      -  
        name: List Artifacts
        run: |
         pwd 
         ls

      - 
        name: configure
        run: |
          ROOTFS="${HOME}/my_root_fs"
          PREFIX="${HOME}/my_root_fs"
          echo "PREFIX=${PREFIX}"
          autoreconf --install
          ./configure --prefix=${PREFIX}

      - 
        name: Build and execute unit test
        run: make test

      - name: Clean build space
        run: make clean
